#!/bin/bash

if ! type -P markdown-pp &>/dev/null; then
    echo "Please install MarkdownPP, e.g.:"
    echo "   pip install MarkdownPP"
    exit
fi

for f in Develop/L10n/Style_Guides/*/README.mdpp; do
    if [ $(head -n1 $f | cut -c 1-4) != "---" ]; then
        echo File "$f" should start with a '---' marker for the variables section
        exit
    fi
    cd $(dirname $f)
    f=$(basename $f)
    md=$(echo $f | sed "s \.mdpp .md ")
    echo "---" > $md
    echo "IMPORTANT NOTE: DO NOT EDIT THIS FILE, instead edit its .mdpp then run ./precheckin.sh" >> $md
    markdown-pp $f | tail -n+2 >> $md
    cd -
done
